# Generated by Django 4.2.2 on 2023-06-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_address_author_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='toronto', max_length=50),
        ),
    ]
